name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Reboot
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:DefineConstants="" ${{env.SOLUTION_FILE_PATH}}
      
    - name: Upload Artifact without ABOVE_S20
      uses: actions/upload-artifact@v3
      with:
        name: Reboot
        path: ${{env.SOLUTION_FILE_PATH}}/x64/Release
        if-no-files-found: warn
        retention-days: 60

    - name: Build RebootS20
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:DefineConstants="ABOVE_S20" ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Artifact with ABOVE_S20
      uses: actions/upload-artifact@v3
      with:
        name: RebootS20
        path: ${{env.SOLUTION_FILE_PATH}}/x64/Release
        if-no-files-found: warn
        retention-days: 60
